name: image-processing
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas=2.1.1
  - requests=2.31.0
  - pillow=9.3.0
  - pip
  - pytest
  - ffmpeg  # ffmpeg from conda-forge

  - pip:
      - azure-storage-blob==12.14.1
      - google-auth-oauthlib==0.4.6
      - google-auth==2.21.0
      - google-api-python-client==2.91.0
      - piexif==1.1.3
      - python-dotenv
